/***********************************************************************/
/*                                                                     */
/*  FILE        :MiconRacer2.c                                         */
/*  DATE        :Sat, Nov 14, 2015                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :34C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

//------------------------------------------------------------------------------
// インクルード
//------------------------------------------------------------------------------
#include <stdlib.h>
#include "mr2_lib.h"

#pragma CREG	_flg_	flg
unsigned int	_flg_;


//------------------------------------------------------------------------------
// メインプログラム
//------------------------------------------------------------------------------

void car_ctrl(	int vector,	int speed )
{
	int motor_r;
 	int motor_l;
	int	vol = abs( vector );

	if( vector > 0 ){
		motor_l = speed;
	}else{
		// minus, zero
		motor_l = speed - vol;
	}
	
	if( vector < 0 ){
		motor_r = speed;
	}else{
		// plus, zero
		motor_r = speed - vol;
	}
	//あとちゃんと計算する
	

	mr2_motor( motor_l, motor_r );
	
	return;
}


void main(void)
{
	unsigned char read_line = 0;
	
	DI();
	if( (_flg_ & 0x02) == 0 ){
		mr2_clock_init();
	}
	mr2_peri_init();
	EI();
	
	while( mr2_pushsw() == 0 );	// スタートボタン押下待ち
    while(1){		
		
		read_line = mr2_sensor_check();		// ラインセンサーから最新情報を取得
		switch(read_line){				// ラインセンサーからの最新情報に応じた処理の分岐
			case SENSOR_AW:				// ライン：なし (コースアウト時)
				car_ctrl( 0, 0 );
				break;
			case SENSOR_LR0:			// ライン：中央 (車体:中央)
				car_ctrl( 0, 100 );
				break;
			case SENSOR_L1:				// ライン：少し左 (車体:ラインより少し右に位置)
				car_ctrl( -30, 100 );
				break;
			case SENSOR_R1:				// ライン：少し右 (車体:中央より少し左に位置)
				car_ctrl(  30, 100 );
				break;
			case SENSOR_L2:				// ライン：左 (車体:ラインより右に位置)
				car_ctrl( -60, 100 );
				break;
			case SENSOR_R2:				// ライン：右 (車体:ラインより左に位置)
				car_ctrl(  60, 100 );
				break;
			case SENSOR_L3:				// ライン：大きく左 (車体:ラインより大きく右に位置)
				car_ctrl( -60, 60 );
				break;
			case SENSOR_R3:				// ライン：大きく右 (車体:ラインより大きく左に位置)
				car_ctrl(  60, 60 );
				break;
			default:					// LEDセンサー定義に存在しない入力信号
				break;					// なにもしない
			}
	}
	 
}


//------------------------------------------------------------------------------
// End of file
//------------------------------------------------------------------------------
